# Generated by Django 4.1 on 2022-08-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShipoingAssress',
            new_name='ShippingAssress',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/%Y/%m/%d'),
        ),
    ]
