# Generated by Django 4.1 on 2022-08-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_shipoingassress_shippingassress_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAssress',
            new_name='ShippingAddress',
        ),
    ]
